### ISSUE TITLE
Support for AMD GPUs?

### ISSUE THREAD

**Issue by kulocora** [Sharrnah/whispering-ui#11]
Thanks for making Whispering Tiger! It's been super helpful for me.

I was using it on my Radeon GPU and couldn't help but think - it would be amazing if Whispering Tiger could incorporate vendor-agnostic whisper ports like https://github.com/Const-me/Whisper so that AMD GPU users could benefit from GPU acceleration too!

Anyways, thanks a lot for all the work!

**Comment by Kieaer** [comment]
This project will help you
https://github.com/vosen/ZLUDA

It's working but whispering-ui doesn't detect GPU. set force CUDA mode and load profile.

**Comment by Sharrnah** [comment]
Hi.

Finally the Update i released today can Support AMD GPU's using Direct-ML.

It is not (yet) available for Faster Whisper, but it works with Transformer Whisper or Original Whisper and most other integrated AI model implementations.

![grafik](https://github.com/user-attachments/assets/43015b0f-1c6a-49d7-afb2-450ee4387659)
![Screenshot 2024-07-20 231549_2](https://github.com/user-attachments/assets/dbfbbd08-33fc-4908-8978-b6905d88e14b)

So i will close this now. Feel free to open a new issue if you find anything. :)
