### ISSUE TITLE
filehash check fails

### ISSUE THREAD

**Issue by drmbt** [Sharrnah/whispering-ui#13]
when trying any of the other models besides the tiny default, the download fails the filehash check, and then tries again, never clearing that point

**Comment by Sharrnah** [comment]
Hello. Sorry to hear that you have issues.

Are you starting it using "Original Whisper" or "Faster Whisper"?
![grafik](https://github.com/Sharrnah/whispering-ui/assets/55756126/86f489a2-0603-4a2f-ac2d-e923a17db01b)

**Comment by Sharrnah** [comment]
i just tested it with the Small Faster Whisper model (float32 and float16) and had no issue with filehash validation.

So my best guess is currently that somehow the file does not get downloaded completely, is modified on download or something along this line.

Are you using some form of Proxy Server that might do things like that?

Can you try the alternative way of downloading? You can disable the UI downloading option under `Settings -> Experimental Options -> Start downloads using the UI.`
![grafik](https://github.com/Sharrnah/whispering-ui/assets/55756126/63662786-2440-42af-8ff9-9fb919da823a)

and see if that solves the issue, as that is using the Python integrated downloader. But you can only see if it finishes in the Logs this way, as the UI has no way of knowing the download progress.

**Comment by ghost** [comment]
Same on my end with faster whisper large distilled v2

**Comment by Sharrnah** [comment]
Sorry. I cannot reproduce the issue.

The file on the server has the same hash as the application expects.

![grafik](https://github.com/Sharrnah/whispering-ui/assets/55756126/0e04f56e-7865-4cc4-8033-ca0565b0bf37)
![grafik](https://github.com/Sharrnah/whispering-ui/assets/55756126/3dbd9ff7-1b7a-4b12-928f-5cdb3ed26d0b)

My only guess is some form of proxy, antivirus etc. modifying the file? Not sure why it would do something like that though.

Can you maybe check if you can download the file manually?

All model links for faster whisper can be found here: https://github.com/Sharrnah/whispering/blob/main/Models/STT/faster_whisper.py#L8

**Comment by Sharrnah** [comment]
There might be an issue with the S3 Hoster that i encountered today as well.

It delivered an outdated file which of course results in the wrong checksum.

I am in contact with the hoster.

**Comment by Sharrnah** [comment]
Issue with the S3 link delivering an outdated file is solved for some time now and i haven't heard any new issue with it.

So i will close this for now. Please let me know if this is still an issue.
