### ISSUE TITLE
User data directory

### ISSUE THREAD

**Issue by babo4d** [Sharrnah/whispering-ui#14]
It is difficult to manage user data like profiles when they have a custom file name at the root level of the app directory. It would be helpful to put user data in a dedicated sub-directory named like `Profiles` or something.

I am thinking in terms of package management, e.g. I want to make a scoop manifest with [persistent data](https://github.com/ScoopInstaller/scoop/wiki/Persistent-data).

**Comment by Sharrnah** [comment]
thats a very good point. I have changed it so in the next update, all profile yaml files are saved in a `Profiles` subfolder.
All existing settings are moved there on the first run.

Will keep this open until the update.

**Comment by Sharrnah** [comment]
This is now in the new version. Existing profiles are automatically moved on first run.
