### ISSUE TITLE
Bad encoding for detection & translate

### ISSUE THREAD

**Issue by Kieaer** [Sharrnah/whispering-ui#16]
![image](https://github.com/Sharrnah/whispering-ui/assets/44261958/52d4cbfd-1e5a-4c9f-b7b0-8a8ca89537c8)

**Comment by Sharrnah** [comment]
Thanks. that is a known issue. Probably the embedded font does not support these characters.

I have to see if i find a more complete font, or if it is some issue with the UI framework itself.

What you can do in the meantime is display the transacriptions using one of the websocket html files, or use the subtitle display plugin.

![grafik](https://github.com/Sharrnah/whispering-ui/assets/55756126/cf93ce12-352e-49ba-abb1-5841d0b77639)

**Comment by Sharrnah** [comment]
Thanks. next version will include Korean characters.
![grafik](https://github.com/Sharrnah/whispering-ui/assets/55756126/4d205b97-d2e9-4365-aa07-024d6788ebf5)

**Comment by Sharrnah** [comment]
New version is out with Korean characterset supported.
