### ISSUE TITLE
How to stop automatically letting Windows get focus?

### ISSUE THREAD

**Issue by OptimisticGeek** [Sharrnah/whispering-ui#18]
Hello author

I have three questions for you. Thank you

1. How can I not wake up Tiger's window automatically after real-time voice recognition detects voice, because I am chatting in VRC at this time, which will make my VRC window lose focus?
2. After I turned off real-time recognition, I used the hotkey for voice recognition, but tiger would also automatically detect voice, which made me very upset
3. After speech recognition, I will reply randomly, and I may not speak at this time. After I don't know what setup, Tiget fixed it on its own.

Here, thank you very much for providing Tiget this very useful software.

This conversation is translated by translation software, I hope there is no unnecessary misunderstanding.

**Comment by Sharrnah** [comment]
Hello @OptimisticGeek 

**For 1.**
This should be disabled by default. 🤔 
To disable this,  you can disable `Focus window on message receive` in Settings -> Experimental Options`.
![grafik](https://github.com/Sharrnah/whispering-ui/assets/55756126/c1dc0201-00cc-46f1-8873-6e5136f347c6)

I will check if there is some bug that this is enabled by accident automatically.

**For 2.**
When you set a Push to Talk Button for the first time,  you should get a message asking if you want to only trigger by the Push-to-Talk button.
![grafik](https://github.com/Sharrnah/whispering-ui/assets/55756126/c0d61c1a-c3d0-4602-a889-fbda379783b6)
This will set `Speech volume Level` and `Speech pause detection` to 0.
This way, the only thing that is used to detect the start and end of a recording is the push of the button.
![grafik](https://github.com/Sharrnah/whispering-ui/assets/55756126/32d02f3f-8044-46f4-a6a4-d0cabc23f2f0)

**For 3.**
I am not 100% sure i understand your quesation correctly. It can happen that transcriptions area "changed" by the AI automatically if it thinks it has more context to understand the spoken sentences. There is not much to do except trying a different AI model type.
For example, Wav2Vec Bert 2.0 goes only from the "sound" of the spoken audio, but in contrast it is a lot less accurate. (And i currently only have English and German models added).

If i understood 3. wrong, i am sorry and would be happy if you explain your 3rd issue again.

**Comment by OptimisticGeek** [comment]
Hello Sharrnah
Thank you very much for your reply

- [X] 1.Because I turned this function on when I was using PC instead of VR
- [ ] 2.I've set the buttons and clicked the Yes button, but Tiger also detects voice in real-time, which I currently avoid by turning the microphone on and off.
- [X] 3.Tiger sends messages on its own when I'm not speaking, which is not what I said. I guess it is because the `Speech volume Level=0` that Tiger recognizes the noise. I avoided this as much as possible by recalibrating the parameters and the way I handled problem 2.

Questions 1 and 3 have been solved, and I have two questions or suggestions:
1. It is hoped that Tiger will have a default configuration built in, which will be used when you create a new Yaml configuration, so that it is more newbie friendly.
2. Is there a translation feature for other people's speech currently or in the future? For example, the voice of other players is translated in VRC to achieve the function of real-time captioning. This can be a huge amount of work because there are multiple people speaking at the same time, and the voiceprint needs to be distinguished to identify who is who's voice and avoid processing all voices as one voice. It's too complicated to think about.

Tiger is a great app. In VRC, they will be surprised to see my own translation and ask me. I will recommend Tiger to them enthusiastically. 

I hope you are happy every day, your Chinese friend OptimisticGeek

![image](https://github.com/Sharrnah/whispering-ui/assets/47779261/c311547e-e74c-437b-81ba-8d54ec1b0d67)

**Comment by OptimisticGeek** [comment]
Ask another question, how to set 'OSC chat prefix', 'OSC transfer split' line feed, I use \n does not work

![image](https://github.com/Sharrnah/whispering-ui/assets/47779261/010a27cc-1355-4f85-bb2a-98ae2a5f36d9)

**Comment by Sharrnah** [comment]
> * 2.I've set the buttons and clicked the Yes button, but Tiget also detects voice in real-time, which I currently avoid by turning the microphone on and off.

Not 100% sure what you mean. In your screenshot, you have disabled `Realtime`, so it should not process your spoken audio in realtime.

Though if you have Speech volume Level and Speech pause detection not set to 0, it will trigger the detection not only by the button press but also on speech volume, which is probably not what you want. So you should keep `Speech volume level` set to 0, and `Speech pause detection` set to 0 as well.

> It is hoped that Tiget will have a default configuration built in, which will be used when you create a new Yaml configuration, so that it is more newbie friendly.

Yes. i already thought about this and is definetly something useful for the future.

> Is there a translation feature for other people's speech currently or in the future?

Yes there is a way. If you use the WASAPI Audio API, you can use your loudspeaker [loopback] device from the microphone list.
This way it captures your PC audio. Together with one of the websocket client overlays (included as html files in the application folder), or using the subtitles plugin, you can get translations of other people.

It is true that it can be difficult when many people are speaking though. To help with this a bit,  you can use earmuff mode in VRChat. I am also currently testing speaker diarization which can detect different speakers, so this could be a feature in the future.

> how to set 'OSC chat prefix', 'OSC transfer split' line feed, I use \n does not work

I haven't tested it with a line break actually and it most likely is not recognized currently. But its a nice idea which could be useful.
There are already some special strings you can use in OSC chat prefix, like `{src}` to get the source language and `{trg}` for the target language.
But this is currently only for the OSC chat prefix field.
Seeing your use-case i think i will add it to OSC transfer split as well. Then it is not so difficult to add a line-break option as well.

**Comment by OptimisticGeek** [comment]
> Though if you have Speech volume Level and Speech pause detection not set to 0, it will trigger the detection not only by the button press but also on speech volume, which is probably not what you want. So you should keep set to 0, and set to 0 as well.`Speech volume level``Speech pause detection`

Thank you, I have figured out how I should set these parameters, these parameters can not be used at the same time, I think this needs a more obvious mutually exclusive interaction reminder

> Yes there is a way. If you use the WASAPI Audio API, you can use your loudspeaker [loopback] device from the microphone list. This way it captures your PC audio. Together with one of the websocket client overlays (included as html files in the application folder), or using the subtitles plugin, you can get translations of other people.

I will first study how to use, thank you, this is very helpful to me.


Thank you for developing Tiger. Your answer made my experience even better!

**Comment by Sharrnah** [comment]
> these parameters can not be used at the same time, I think this needs a more obvious mutually exclusive interaction reminder

They can be used at the same time. :) Though it most likely is not what you expected.
Setting `Speech volume Level` above 0, will trigger the detection by audio volume.
Setting a Push to Talk button will trigger the detection with the push of a button.

If both are set, both events can start the transcription process.
I added that message box when someone enters a push to Talk key, and i wrote `0 = Disabled` hint in the description.
But maybe it is not obvious enough and i really need to disable one or the other completely depending on if a push to talk button is set.

Thanks for trying it and for the feedback. And feel free to open a new issue if you find anything else or need more help.

Also feel free to join the Discord Server if you feel like it, with more direct help and some fun with an AI bot. :)
https://discord.gg/V7X6xa2B2v
