### ISSUE TITLE
Error using WASAPI-Loopback

### ISSUE THREAD

**Issue by OptimisticGeek** [Sharrnah/whispering-ui#19]
Hello,Sharrnah

The program reported an error after setting the Loopback. . I can't solve this problem by myself, so I have to come here to trouble you.

This is my configuration image，Note that Audio Input(mic) uses a **Loopback**.
![image](https://github.com/Sharrnah/whispering-ui/assets/47779261/ad75606a-6421-4ed9-8f94-e4ccce8eea73)

An error occurred when tiger started loading
![image](https://github.com/Sharrnah/whispering-ui/assets/47779261/3ef63e98-a4b8-4245-826c-e39b0bafa947)

This is the complete error log image
![image](https://github.com/Sharrnah/whispering-ui/assets/47779261/e5b777a0-19bb-4819-b7ad-10531295e09c)

Your Chinese friend,OptimisticGeek

**Comment by Sharrnah** [comment]
Looking at your headset, my guess is that it has issues with 7.1 surround sound.

It can't handle so many channels. Since i don't have 7.1 surround sound, its difficult for me to test.
Can you try it with regular stereo sound? That should definetly work.

**Comment by OptimisticGeek** [comment]
I found out through your code that my headphones are mono induced.
![image](https://github.com/Sharrnah/whispering-ui/assets/47779261/a74de83d-68c1-4da0-844a-870e37389321)

Yes, my headphones have 7.1 surround sound. I'm trying to figure out how to set up the driver for this headset. I'll give you the answer later.

**Comment by OptimisticGeek** [comment]
In my tests, 7.1 surround sound will report an error whether it is turned on or off.Because my headphones only support one channel,It does not support dual channels!

**Comment by Sharrnah** [comment]
one channel should also work.

Thats what it uses as fallback in the code you mentioned.

I think you confuse the microphone (which is mostly 1 channel)
and your loudspeaker in the headset (in your case probably 8 channels [7+1])

Another way that you can try is using Voicemeeter https://vb-audio.com/Voicemeeter/

with that, you can route your PC audio to a VAIO Input which again can route to your Headset.
When you now use the Loopback device of the VAIO Input, i think it could work. Though i never tested it with surround sound.

I will see if i can find a sultion with more than 2 channels of audio. So i will keep this issue open.

**Comment by OptimisticGeek** [comment]
> I think you confuse the microphone (which is mostly 1 channel) and your loudspeaker in the headset (in your case probably 8 channels [7+1])

I do not understand the difference between single channel and dual channel, but through the online information to look up the following picture, the problem seems to be due to the limitations of my headset hardware.

Note the `Input setttings -> format` option，I'm guessing the 1 and 2 in your code are based on that.
![image](https://github.com/Sharrnah/whispering-ui/assets/47779261/5f86d46b-921c-49d0-a446-f4d680d7e9ae)

[Screenshot information link](https://www.bilibili.com/read/cv26015134/#%E4%B8%80%E3%80%81%E5%8F%8C%E5%A3%B0%E9%81%93%E6%98%AF%E4%B8%AA%E5%95%A5%EF%BC%9F)
![image](https://github.com/Sharrnah/whispering-ui/assets/47779261/e31c67e7-b1a8-42f7-a7c1-870491312b8e)

> Another way that you can try is using Voicemeeter https://vb-audio.com/Voicemeeter/

Yes, I have achieved real-time translation of in-game sounds in this way. And by opening a new process to achieve the voice translation function, thank you very much.

> I will see if i can find a sultion with more than 2 channels of audio. So i will keep this issue open.

Okay, I won't close this comment myself anymore.

**Comment by OptimisticGeek** [comment]
Note that my headset is a USB device with microphone and speaker in one, not two 3.5mm plugs (speaker plug, microphone plug)

**Comment by Sharrnah** [comment]
> Note the `Input setttings -> format` option，I'm guessing the 1 and 2 in your code are based on that.

Yes. But in your screenshot you edit your microphone. Since you want to use [Loopback] it would actually be the loudspeakers (Output) device.

(Loopback is a feature of WASAPI that allows recording of outgoing audio, so everything that is played to the loudspeakers)

Though it is possible that Windows does not allow changing the channels for output devices.
(At least i don't see any option for that, but i only have 2 to begin with.)

**Comment by OptimisticGeek** [comment]
Through the use of Voicemeeter, I understood some principles of WASAPI.
Sharrnah, thank you for your answer!

**Comment by Sharrnah** [comment]
Should be fixed in the next release version: https://github.com/Sharrnah/whispering/pull/24

I haven't really tested it with more than 2 channels since i don't have anything with more than 2. But i am relatively confident it (should) work. 😬 

I will keep this issue open until the next version release.

**Comment by OptimisticGeek** [comment]
Ok, this is great, I will test this issue after the new version is released!
![04538544](https://github.com/Sharrnah/whispering-ui/assets/47779261/3e609703-385c-4306-ada5-824599b2cef0)

**Comment by Sharrnah** [comment]
I just released the new Update.
- This should now support audio devices with more than 2 channels by resampliing them seperately and later remerging them.

I will close this. Let me know if it works with the new update.
