### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by Maol-commits** [Sharrnah/whispering-ui#2]
Unexpected EOF when I'm downloading for the first time
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/10917426/215348740-2d8f128c-551a-4859-9947-32200402bbea.png">

**Comment by Sharrnah** [comment]
I hope the last update fixes this,
but it needs some more testing so i am keeping this issue open for now.

**Comment by Sharrnah** [comment]
I will close it now. Could not get any EOF error.

And even when it happens, it should now resume download which means it will pick up the download where it stopped before when starting it again.

If this happens again, feel free to open a new issue.
