### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by yahya301** [Sharrnah/whispering-ui#24]
erro whwn connecting to websoket 
![Capture](https://github.com/user-attachments/assets/758a3877-430d-48ba-b3e2-f9b61462473f)

**Comment by Sharrnah** [comment]
can you copy the log from `Advanced -> Logs` and paste it here?
There seems to be an error. Just not sure where it exactly occured based on your screenshot alone.

**Comment by yahya301** [comment]
![logs](https://github.com/user-attachments/assets/dd2c7a60-aad9-4280-8542-b8cb565836b0)
 i can not copy the logs . i hope screen is enough

**Comment by Sharrnah** [comment]
yes. thanks.

One big thing is definetly running it from OneDrive. I heard from multiple people that this is problematic.
So please try to run it from a normal harddrive first. Maybe that already fixes the issue.

Copy should work if you press the `Copy Log` Button btw. :)

**Comment by yahya301** [comment]
thanks . onedrive was the issue 

it is working fine now
